
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 12 15:13:05 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 47;
  public static final int CONST = 19;
  public static final int LPAREN = 11;
  public static final int SEMI = 21;
  public static final int CONTINUE = 25;
  public static final int FOR = 17;
  public static final int MINUS = 33;
  public static final int STATIC = 18;
  public static final int RPAREN = 12;
  public static final int AND = 31;
  public static final int LT = 41;
  public static final int OR = 32;
  public static final int LTEQU = 42;
  public static final int COMMA = 14;
  public static final int BOOL_IDENT = 48;
  public static final int CLASS = 15;
  public static final int INC = 29;
  public static final int DIV = 38;
  public static final int PLUS = 35;
  public static final int IFEQU = 39;
  public static final int IF = 23;
  public static final int LSQBRACE = 5;
  public static final int DOT = 8;
  public static final int EOF = 0;
  public static final int RETURN = 26;
  public static final int EQUAL = 20;
  public static final int LAMBDA = 7;
  public static final int NEW = 34;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int NUMBER = 45;
  public static final int IDENT = 46;
  public static final int BREAK = 24;
  public static final int VOID = 10;
  public static final int COLON = 22;
  public static final int LBRACE = 3;
  public static final int ELSE = 13;
  public static final int GTEQU = 44;
  public static final int READ = 27;
  public static final int NOTEQU = 40;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 16;
  public static final int PROG = 2;
  public static final int NAMEPACE = 9;
  public static final int RSQBRACE = 6;
  public static final int DEC = 30;
  public static final int DIVISION = 37;
  public static final int GT = 43;
  public static final int PRINT = 28;
}

